version: '2.1'
services:
  mq:
    image: 'aplregistry.aarnet.edu.au/cloudservices/eos/eos-citrine-mq:${EOS_BUILD_TAG}'
    env_file:
      - ./files/eos-docker.env
    hostname: mq.shard
    networks:
      shard:
        aliases:
          - mq.shard
    volumes:
      - './devmnt/eos/eos.keytab:/etc/eos.keytab:ro'
      - './devmnt/eos/qdb.keytab:/etc/qdb.keytab:ro'
      - 'eos_logs:/var/log/eos'
      - 'eos_config:/var/eos/config'
      - 'eos_md:/var/eos/md'
      - 'eos_ns_queue:/var/eos/ns-queue'
    environment:
      EOS_SET_MASTER: 1
    healthcheck:
      test:
        - CMD-SHELL
        - nc -zv localhost 1097
      interval: 10s
      timeout: 5s
      retries: 5

  mgm:
    image: 'aplregistry.aarnet.edu.au/cloudservices/eos/eos-citrine-mgm:${EOS_BUILD_TAG}'
    privileged: true
    env_file:
      - ./files/eos-docker.env
    hostname: mgm.shard
    networks:
      shard:
        aliases:
          - mgm.shard
    volumes_from:
      - mq
    depends_on:
      qdb:
        condition: service_healthy
    environment:
      EOS_SET_MASTER: 1
      EOS_GRAPHITE: 'false'
    healthcheck:
      test:
        - CMD-SHELL
        - eos ns | grep booted
      interval: 10s
      timeout: 5s
      retries: 5

  fst:
    image: 'aplregistry.aarnet.edu.au/cloudservices/eos/eos-citrine-fst:${EOS_BUILD_TAG}'
    env_file:
      - ./files/eos-docker.env
    hostname: fst.shard
    networks:
      shard:
        aliases:
          - fst.shard
    volumes:
      - './devmnt/eos/eos.keytab:/etc/eos.keytab:ro'
      - 'eos_logs:/var/log/eos'
      - 'eos_disks:/disks'
    depends_on:
      - mgm
    environment:
      EOS_MGM_URL: 'root://mgm.shard'
    healthcheck:
      test:
        - CMD-SHELL
        - nc -zv localhost 1095
      interval: 10s
      timeout: 5s
      retries: 5

  qdb:
    image: 'aplregistry.aarnet.edu.au/cloudservices/eos/eos-citrine-qdb:${EOS_BUILD_TAG}'
    env_file:
      - ./files/eos-docker.env
    hostname: qdb.shard
    networks:
      shard:
        aliases:
          - qdb.shard
    depends_on:
      - mq
    volumes:
      - './devmnt/eos/eos.keytab:/etc/eos.keytab:ro'
      - './devmnt/eos/qdb.keytab:/etc/qdb.keytab:ro'
      - 'eos_logs:/var/log/eos'
      - 'quarkdb_ns:/var/lib/quarkdb'
    environment:
      EOS_QDB_DIR: /var/lib/quarkdb/eosns
      EOS_QDB_PORT: '7777'
      EOS_QDB_MODE: raft
      EOS_QDB_CLUSTER_ID: 3d659c1a-e70f-43f0-bed4-941a2ca0765b
      EOS_QDB_NODES: 'qdb.shard:7777'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '-h'
        - localhost
        - '-p'
        - '7777'
        - raft-info
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: 'aplregistry.aarnet.edu.au/cloudservices/minio/shard:${EOS_BUILD_TAG}'
    build:
      dockerfile:  Dockerfile.aarnet
      context: ../../
    networks:
        shard:
          aliases:
          - minio.shard
    env_file:
      - ./files/minio.env
    ports:
    - 9000:9000
    volumes:
    - './devmnt/eos/eos.keytab:/etc/k8screds/eos.keytab:ro'
    - minio_stage:/stage
    depends_on:
    - fst
    - mq
    - mgm
    - qdb
    healthcheck:
      test:
        - CMD
        - curl
        - http://127.0.0.1:9000
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  eos_disks:
    driver: local
  eos_md:
    driver: local
  eos_ns_queue:
    driver: local
  eos_config:
    driver: local
  eos_logs:
    driver: local
  quarkdb_ns:
    driver: local
  minio_stage:
    driver: local

networks:
  shard: null
